### ISSUE TITLE
RFE: add support for pre-made rootfs

### ISSUE THREAD

**Issue by ghost** [systemd/mkosi#111]
In case of cross-compiled distro (https://www.yoctoproject.org/ for example) the root FS comes as archive. Would be nice if mkosi could just take that rootfs.tar.gz and use it instead of calling debootstrap or equivalent.

**Comment by poettering** [comment]
i figure if "mkosi.rootfs.tar.gz" or so exists, we could just use that...

**Comment by poettering** [comment]
(happy to take a patch for that)

**Comment by poettering** [comment]
I figure the "mkosi.skeleton/" idea  suggested in #106 might be closely related to this concept. After all "mkosi.skeleton/" + the ability to do "NOP" distribution installs should make this possible

**Comment by lucasdemarchi** [comment]
yes, btw skeleton may be a tarball.

**Comment by johannbg** [comment]
Hmm is the idea here to introduce a new mkosi distribution concept embedded or tarball in which the user would what take the rootfs.tar.gz ( or something like Gentoo Stage tarball ) put the tar ball in the mkosi.skeleton/ directory, create a mkosi distribution file ( mkosi.embedded or mkosi.tarball ) which ignores [Packages] altogether and basically the content of the tarball is just extracted on the image which is based on the partition layout or something like that.

The requirement is always that systemd is present right ( so Gentoo official stage tarball would not work since systemd is not the default init system in Gentoo  ) anyway afaikt 

A ) Lucas has already implemented this via support for skeleton tarballs and the RFE can be closed 
B) A new embedded/tarball distribution concept needs to be invented ( which requires somekind of brainstorming ) and the RFE remains open.

FYI the reporter has not commented on this issue since he created it so arguably unless the plan is going the option B route this issue can just be closed ( Yocto has bitbaker to create images )

**Comment by DaanDeMeyer** [comment]
We have support for skeleton tarballs now so let's close this
