### ISSUE TITLE
Documenting and bumping minum requirements

### ISSUE THREAD

**Issue by behrmann** [systemd/mkosi#1124]
Since this came up again yesterday: We are currently on Python 3.7, which is the oldest supported Python version. This means that mkosi runs on Debian buster, which is currently oldstable. Debian bullseye, the current stable, has been released almost two years ago and the next Debian release is not too far off.

At least for Debian we have
- current release: python 3.9, systemd 247 (251 in backports including repart, homed and userdb seperately installable), util-linux 2.33.1
- old release: python 3.7, systemd 241 (247 in backports), util-linux 2.36.1

Fedora and Arch are obviously ahead and more current (Gentoo probably as well), but I have no idea what the lowest supported versions for OpenSuse or the different RHEL flavours are (and we probably don't want to wait for RHEL7 to age out in 2 years). 

Cutting off 3.7 and maybe jumping straight to 3.9 would give as a few utility functions on `Path` instances, idempotent file removals there too, and the walrus operator and generally less mental gymnastics whether things one tries to do are supported.

Dropping pre-247 systemd would allow us at least one workaround as well (in `ensure_networkd`).

I guess it's too early to move to using repart, but maybe we could document our minimum requirements in terms of needed tools.

**Comment by mrc0mmand** [comment]
The default python RHEL 8 is stuck with is Python 3.6 (iirc), but it has also packages/modules for 3.8 and 3.9 (so far).

RHEL 7 is also stuck with Python 3.6 and I don't see any newer version even in EPEL, but as you said I don't think this is something we should block ourselves on. 

And just for completeness, RHEL 9 is currently on Python 3.9.

**Comment by DaanDeMeyer** [comment]
repart was missing drop-in directories support and support for multiple definition directories which only got implemented just now so we'll need to wait for 252 before we can use it. That'll also give us access to systemd-dissect --umount as well. But generally we're stuck waiting out another round of LTS releases if we want to keep compat with those before we can think about using repart and systemd-dissect instead of the current stuff.

I'd say the biggest thing in 3.9 would be that we'd be able to use `list[T]` and such for typing. But overall I don't think the additional niceties are worth bumping the minimum python version, we get along fine with the current version. It's systemd where bumping the minimum version would give us major benefits.

I almost want to start distributing statically linked versions of nspawn, repart, and dissect with mkosi just so we can finally move forward a bit instead of waiting ages for distros to catch up.

**Comment by behrmann** [comment]
> I'd say the biggest thing in 3.9 would be that we'd be able to use `list[T]` and such for typing. But overall I don't think the additional niceties are worth bumping the minimum python version, we get along fine with the current version. 

Yes, it's not a major issue, but if we don't want to wait for the end of RHEL7 (whose default Python version we've already left in the rearview mirror) and 3.9 is available on all other platforms, it would make sense to make the switch. Even a switch to 3.8 would be a small quality of life improvement, depending on what LTS of Ubuntu we'd want to target (I haven't yet checked Python versions there).

**Comment by cryptoknight** [comment]
FYI RHEL 8 (and older, I presume) are also currently broken because the [old sfdisk](https://github.com/systemd/mkosi/issues/879) fix was [dropped](https://github.com/systemd/mkosi/commit/046abbb17f21d097e068b41ed0565907790522f7). RHEL 8 seemed otherwise fine when running under python 3.9.

**Comment by DaanDeMeyer** [comment]
We moved to systemd-repart and python 3.9, so let's close this issue
