### ISSUE TITLE
Cross-Architecture support in mkosi: permit creating arm images from x86-64 and suchlike

### ISSUE THREAD

**Issue by Pillar1989** [systemd/mkosi#138]
Hi
    I want  to use mkosi create armhf rootfs image. Is there any docments about this?

**Comment by poettering** [comment]
Sorry, but cross-building is something mkosi can't do for you, as it is built around dnf/debootstrap and such, and they don't support that. Sorry!

**Comment by poettering** [comment]
So, as it turns out I was wrong, dnf actually supports bootstrapping non-native archs, and I think it would make a ton of sense to support this in mkosi. Hence, let's reopen this, and let's make this an RFE issue.

Adding this should be fairly straightforward implementation-wise, given the hard work is already done in dnf/qemu.

**Comment by poettering** [comment]
https://npmccallum.gitlab.io/post/cross-architecture-roots-with-dnf/

**Comment by fsateler** [comment]
deboostrap also has support for cross-installing, but it's a bit more involved https://wiki.ubuntu.com/ARM/RootfsFromScratch/QemuDebootstrap

**Comment by gyscos** [comment]
pacstrap also supports cross-architecture installations by specifying an alternative config file with `-C`.

**Comment by DaanDeMeyer** [comment]
We have an --architecture switch now so I think this can be closed.
