### ISSUE TITLE
image cache files are being copied into the target image if not running from a git project

### ISSUE THREAD

**Issue by fthiery** [systemd/mkosi#151]
That one's pretty fun:

```
            if use_git:
                copy_git_files(args.build_sources, target, git_files=args.git_files)
            else:
                ignore = shutil.ignore_patterns('.git', '.mkosi-*')
                shutil.copytree(args.build_sources, target, symlinks=True, ignore=ignore)
```
This means that in a non-git folder, raw images are being copied into it, resulting in an out of space error.

```
$ ls
$ image.raw.cache-pre-dev  image.raw.cache-pre-inst  mkosi.build  mkosi.default
$ sudo mkosi -if
...
‣ Detaching image file complete.
...
[Errno 28] No space left on device'
```

**Comment by poettering** [comment]
As discussed elsewhere I figure we really should implicitly filter out all out output files when copying the tree.

**Comment by fthiery** [comment]
This could work too, but not:
- if you have multiple config files in the directory (-C)
- if you are keeping backup images in the working directory
- if you change the output filename (then subsequent builds would include images built before)

I guess that the current default behaviour is fine as long as you are using git (i.e. if the file hasn't been committed, i believe it is bypassed -- anyone would think twice commiting a large file). In that case, filtering is based on that fact.

Which points back to the original issue: how do you filter out without git, which can be partially handled by skipping known output files (with the aforementioned limitations), or on extensions (but the .raw extension is too common to be used as filter).

I still am convinced that a mandatory output folder would solve the problem most elegantly, but it would break stuff.

Last, i believe that the current folder is copied into the target only if no source folder has been explicitly defined (--build-sources ?) , so i guess the problem doesn't happen in that case.

The biggest issue here was that including large files was completely silent, i really think that a simple log message would improve the situation, on top of an additional config flag defining additional filters for instance; the log message could suggest to blacklist that file for instance, using this flag.

**Comment by poettering** [comment]
Hmm, so I thought a bit about this. We already ignore the cache files now by default, and "mkosi" refuses to operate anyway if the output already exists. Hence I figure we are actually fine already, as long as the user always uses the same output file in the local dir, all should be good, no fixes necessary.

But yeah, this falls apart as soon as the user creates multiple images within the same dir, either by having multiple mkosi.default files lying around, or by overriding the output temporarily with `-o`. Given that `-o` can take any free-form string we can't really detect all possible other images that the user could generate.

Hence I figure we should probably "solve" with the following strategy:

1. implement the concept of an "output directory". All output will be placed there, and the whole directory would be excluded by default from image generation. We'd add auto-discovery of the dir: if "mkosi.output/" exists and is a dir, and "-o" specifies a filename containing now slashes, we'd place the output there, instead of the working directory.

2. Document this behaviour, so that people grok what's going on, and point them towards using "mkosi.output/" if they want to build multiple images from the same working directory.

Does that make some sense?

**Comment by fthiery** [comment]
I think so, yes; however
- it would be wise to add some prominent logging strongly suggesting to use the output directory if not running from a git project
- we should still add the predicted output name to the exclusion filter (i believe it is currently not the case, is it ?)

**Comment by poettering** [comment]
> we should still add the predicted output name to the exclusion filter (i believe it is currently not the case, is it ?)

But that's unnecessary afaics. I mean, we refuse operation anyway if the output already exists. And if you add "-f" then we delete the output before we start operation. Either way, it's not gonna happen that the output already exists while we are running.

**Comment by fthiery** [comment]
Alright, sounds good then.

**Comment by fthiery** [comment]
What is missing now is the exclusion filter for the cache images, sorry for the confusion.

**Comment by poettering** [comment]
So I prepped #165 now, which implements mkosi.output/. PTAL

**Comment by fthiery** [comment]
Seems good, thanks. I'll test tomorrow maybe. I would still add some informational warning in case a file bigger than 500 Mb is being copied onto the target, or if the file ends with the .raw extension (just in case), along with suggesting creating a mkosi.output folder.
