### ISSUE TITLE
Flexible sysext inclusion

### ISSUE THREAD

**Issue by MariusSchiffer** [systemd/mkosi#1643]
I would like to generate an image where a separate preset (before the final one) generates a tree that ends up in a separate sysext partition.
Ideally, I would also like to turn the preset and the partition on/off using command line modifiers (like `--preset`).

I can already achieve parts of this by copying in the extension preset's output to a separate directory in /usr (using ExtraTrees) and then CopyFiles= that into the separate partition.

Is there already an elegant way for this? Maybe implementing a conditional switch in repart definition files is the way to go

**Comment by DaanDeMeyer** [comment]
We could maybe add a modifier to systemd-repart to make sure paths are resolved relative to the host instead of the given root, but I'm not convinced that's a good idea. Can you describe your use case in detail?

**Comment by MariusSchiffer** [comment]
I'm generating a base image that runs on most devices and is built using presets `base,initrd,final,bootable`.  
For some devices I also need an extended image that contains a proprietary service that should only exist on these special images.
I build this using another preset `proprietary` with `Overlay=yes`.

When I'm merging this all onto a single `/usr` partition, I can select the presets with `--preset=base --preset=initrd --preset=final --preset=proprietary --preset=bootable`, and for normal images I can leave out the `proprietary` preset. 
I would like an option where I could instead exclude a preset. (I can also implement this in a PR, just want some feedback first).

Ideally, I'd like to have the proprietary preset instead on a separate partition, as I use the split partition output from repart for my update packages. But for this I need an extra repart file that only includes these specific files from the preset.
If these do not exist, repart complains.

**Comment by DaanDeMeyer** [comment]
So you can now set `Presets=` to set the default presets to build and use `Dependencies=` to declare dependencies between presets. This allows you to declare a configuration in which case `proprietary` is not build by default.  You can then have a dropin in `final` or `bootable` with a match section that only installs the `proprietary` preset when required. Or use the new `Include=` switch instead of a `Match` section.

systemd-repart will learn a new switch `--copy-source` soon which we'll switch to at some point in mkosi. That would make `CopyBlocks=` directives get interpreted relative to the host which should allow you to include the `proprietary` preset output as a separate partition.

Since the basic functionality in mkosi for this is already and it's going to take quite a while before we'll start using `--copy-source` for repart, I'm going to close this one as completed. Let me know if something to make this work is still missing.
