### ISSUE TITLE
KernelCommandLine is reversed

### ISSUE THREAD

**Issue by MariusSchiffer** [systemd/mkosi#1707]
When specifying multiple arguments in one `KernelCommandLine` config option, the kernel cmdline is reversed.

I guess this is due to the list parsing insertion here: https://github.com/systemd/mkosi/blob/main/mkosi/config.py#L384

Ex.: `KernelCommandLine=quiet loglevel=3` results in `Kernel Command Line: loglevel=3 quiet`.
Sometimes the ordering is important though.

**Comment by gdiscry** [comment]
This issue has a wider impact. All options are concerned, but particularly the lists where the order is important (such as environment variables).

The configuration is parsed from the highest priority to the lowest, starting with the command line arguments and continuing with the configuration files.

Options with a single value should use the one with the highest priority and lists should be ordered from lowest priority to highest.

However, there are a few cases where the priority is reversed:

- As noticed, a list of values passed as a single string joined by a delimiter are reversed.
- Also, an option set multiple times on the command line gives a higher priority to its earlier values than the later ones. The inverse is usually expected so that a command line option can be overridden by a later one.
