### ISSUE TITLE
Option to create additional bootloader entries

### ISSUE THREAD

**Issue by septatrix** [systemd/mkosi#1807]
Based on my understanding the default is to use systemd-boot as the bootloader. It would be great to support adding additional bootloader entries (e.g. kernel with different cmdline options set). This can be used to boot e.g. in a rescue mode or an installation target.

**Comment by DaanDeMeyer** [comment]
For Type 1 boot loader entries, we're unlikely to support this in mkosi directly, you can just add those in via a dropin. Making this work is still missing support in systemd-boot to apply the cmdline from the Type 1 entry to a UKI I think.

For Type 2 entries, this needs support in the UKI spec first, so that multiple cmdlines can be embedded in a UKI and a menu is shown on boot to chose which cmdline to boot into.

So nothing we can do in mkosi for this currently. You can search for existing issues or open a new one in the systemd repo to get this stuff implemented there so we can use it.

**Comment by DaanDeMeyer** [comment]
I think it makes more sense to implement some kind of profile support for kernel-install with which you could define multiple kernel-install profiles, each with different cmdline arguments. We'd then make use of this in mkosi. Can you open an issue on the systemd repo instead to add something like this to kernel-install if one doesn't exist yet?
