### ISSUE TITLE
mkosi won't clean up btrfs snapshots

### ISSUE THREAD

**Issue by zealws** [systemd/mkosi#182]
I'm running mkosi to build a btrfs snapshot debian image.

It's trying to clean up the build directory (`.mkosi-sbcfbsy1/root`) by deleting it with `os.rmdir`, which fails because `/home` and `/var` (among others) are btrfs subvolumes within the build root.

It should be calling `btrfs subvolume delete` instead of `os.rmdir` when using btrfs subvolumes to do the build.

The command I ran:
```
$ mkosi -t subvolume -o debian-base -r stable -d debian
```

The btrfs subvolume listing after the build:

```
root@drcid /var/lib/sandbox $ btrfs subvolume list .
ID 288 gen 19556 top level 5 path var/lib/sandbox
...
ID 300 gen 19536 top level 288 path .mkosi-sbcfbsy1/root
ID 301 gen 19536 top level 300 path .mkosi-sbcfbsy1/root/home
ID 302 gen 18611 top level 300 path .mkosi-sbcfbsy1/root/srv
ID 303 gen 19536 top level 300 path .mkosi-sbcfbsy1/root/var
ID 304 gen 18613 top level 303 path .mkosi-sbcfbsy1/root/var/tmp
ID 305 gen 18614 top level 303 path .mkosi-sbcfbsy1/root/var/lib/machines
```

I was using [master](https://github.com/systemd/mkosi/commit/7f82d90f349ac618c41e43d7dd666eb411a4b08f). [Full logs](https://gist.github.com/zfjagann/41f4b439f4d54ddde3d563f04fe6d9e5)

**Comment by zfjagann** [comment]
The build failed because some deb packages failed to authenticate correctly, but I'm not sure if that's an issue with mkosi or not.

**Comment by gdiscry** [comment]
I have the same issue when the build fails.

The issue comes from the workspace being a `tempfile.TemporaryDirectory` (/var/lib/sandbox/.mkosi-sbcfbsy1 in your case). When the build fails, the subvolumes remain in the workspace and block the automatic cleanup of the temporary directory with `shutil.rmtree`.

From what I've seen, it's not possible to hook into the cleanup of `tempfile.TemporaryDirectory`. Managing the workspace would probably require a customized implementation.

**Comment by barcharcraz** [comment]
This is made worse because even when you are not using the btrfs image types snapshots still get created!
