### ISSUE TITLE
tips to keep images as small as possible

### ISSUE THREAD

**Issue by fedelibre** [systemd/mkosi#184]
I wonder if you could have a look at my little project and tell me if there's anything I can do to keep the final image smaller.
The image is generated by [this file](https://github.com/fedelibre/LilyDevOS/blob/master/fedora/mkosi.fedora-lxqt). Compressed image of latest release is 1,9GB. My desired size would be within 1,2GB.

Thanks in advance

**Comment by fedelibre** [comment]
I guess that the only thing I can do is installing single packages instead of Fedora group @lxqt-desktop-environment.

BTW, a nice have would be to prevent a package from being installed. So I may still use the group package and specify which packages of that group should not be installed.
What do you think about it?

**Comment by DaanDeMeyer** [comment]
Image size is more of a distribution issue rather than a mkosi issue so there's not much for mkosi to do on that front. There might be some stuff to do on mkosi's side as well but that should be supported by some more concrete data. Ignoring packages might be nice to support if it's something supported by most or all package managers of the supported distros (I know pacman has IgnorePkg) but please open a new issue for that if it's still necessary.
