### ISSUE TITLE
git-describe fails due to dubious ownership

### ISSUE THREAD

**Issue by medhefgo** [systemd/mkosi#1918]
From a systemd mkosi build:
```
[13/2287] Generating version.h with a custom command
fatal: detected dubious ownership in repository at '/work/src'
To add an exception for this directory, call:

	git config --global --add safe.directory /work/src
```
In this case it causes the build to fall back on "254-" as the version tag.

**Comment by behrmann** [comment]
I'm not quite sure this is our bug. A few releases ago (I don't exactly remember when) git started to no longer run commands in repos owned by other users, since this might be a vector to for malicious code for people that automatically run things when entering git repositories.

I assume we trigger this because the repo is owned by the root user in the user namespace, which has a different GID from the user running mkosi. 

I'm not sure whether we can fix this bug in all generality, i.e. inject a local config at certain points, since people might clone repos during scripts. Probably setting the config globally and have it work for `/work/src`, might be the best option.

**Comment by DaanDeMeyer** [comment]
Let's close this one since `MKOSI_UID` and `MKOSI_GID` are now made available to run commands the user invoking mkosi which makes it possible to avoid issues like this by running the command as the user invoking mkosi
