### ISSUE TITLE
Additional repositories capability for openSUSE

### ISSUE THREAD

**Issue by uningan** [systemd/mkosi#204]
I would like to have extra repositories feature also for openSUSE

**Comment by fedelibre** [comment]
Why *also* for openSUSE?

[The manual page](https://github.com/systemd/mkosi/blob/master/mkosi.md#command-line-parameters) lists a `--repository` option, which is available [since 2016](https://github.com/systemd/mkosi/commit/600e33e49d085c18fcd34dcbd5b0cf9c3f3a07b3).

IIUC it allows only to set a different URL, not to specify a precise repository.
For example, I'd like to add stretch-backports to a Debian image and --repositories option will not help. I'll have to use `mkosi.postinst`.

**Comment by DaanDeMeyer** [comment]
We have --repository-directory now, it might still need to be integrated with zypper but please open a separate issue for that if you need it.
