### ISSUE TITLE
Can't remove `vmlinuz` for `Format=UKI` output

### ISSUE THREAD

**Issue by Winterhuman** [systemd/mkosi#2088]
Host OS: Arch Linux
`uname`: Linux 6.6.2-arch1-1 #1 SMP PREEMPT_DYNAMIC x86_64 GNU/Linux
`mkosi`: v19

# Description

Despite what the `mkosi-initrd/mkosi.conf` file in the repo states about `vmlinuz` being pointless to install in `initramfs` images, removing `/usr/lib/modules/*/vmlinuz` with `RemoveFiles` leads to the following error:

```
‣ A kernel must be installed in the image to build a UKI
```

There's a similar warning for st-stub too:

```
‣ sd-stub not found at /usr/lib/systemd/boot/efi/linuxx64.efi.stub in the image
```

Presumably, this could be stripped from initramfs images too without affecting bootability.

Fixed by: https://github.com/systemd/mkosi/pull/2164/commits/b7d4ce19a22fa3a08684a3d58b6d367015136ae5

# Config

Reproducible for all Arch Linux configs containing `Format=uki` and `RemoveFiles=/usr/lib/modules/*/vmlinuz`.

**Comment by DaanDeMeyer** [comment]
The comment is for initrds, not for UKI outputs. To produce the UKI outputs, we need a kernel, stub, etc which we pick up from the root directory. This means that if you remove any of the components using RemoveFiles=, we won't be able to find them and won't be able to produce the UKI as a result.

To fix this we would have to copy the components required to build the UKI to some temporary directory before removing any files so that they're still available afterwards.

**Comment by Winterhuman** [comment]
https://github.com/systemd/mkosi/pull/2164 is now merged, and it includes https://github.com/systemd/mkosi/commit/b7d4ce19a22fa3a08684a3d58b6d367015136ae5 which fixes this, closing issue. Thanks!
