### ISSUE TITLE
trouble with git worktree

### ISSUE THREAD

**Issue by keszybz** [systemd/mkosi#22]
I called mkosi from a git workdir (with .git a symlink to some other place), and got the following tb
```
‣ Running build script...
['systemd-nspawn', '--image=/var/tmp/.mkosi-aw49u5ok', '--as-pid2', '--private-network', '--register=no', '--bind', '/var/tmp/mkosi-k8yood73/dest:/root/dest', '--setenv=WITH_DOCS=0', '--setenv=DESTDIR=/root/dest', '--setenv=SRCDIR=/root/src', '--chdir=/root/src', '/root/mkosi.build']
Spawning container mkosi-aw49u5ok on /var/tmp/.mkosi-aw49u5ok.
Press ^] three times within 1s to kill container.
+ git clean -dfqx
fatal: Not a git repository (or any of the parent directories): .git
Container mkosi-aw49u5ok failed with error code 128.
Traceback (most recent call last):
  File "../mkosi/mkosi", line 1567, in <module>
    main()
  File "../mkosi/mkosi", line 1563, in main
    build_stuff(args)
  File "../mkosi/mkosi", line 1515, in build_stuff
    run_build_script(args, workspace.name, raw)
  File "../mkosi/mkosi", line 1504, in run_build_script
    subprocess.run(cmdline, check=True)
  File "/usr/lib64/python3.5/subprocess.py", line 711, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['systemd-nspawn', '--image=/var/tmp/.mkosi-aw49u5ok', '--as-pid2', '--private-network', '--register=no', '--bind', '/var/tmp/mkosi-k8yood73/dest:/root/dest', '--setenv=WITH_DOCS=0', '--setenv=DESTDIR=/root/dest', '--setenv=SRCDIR=/root/src', '--chdir=/root/src', '/root/mkosi.build']' returned non-zero exit status 128
```

**Comment by poettering** [comment]
@keszybz hmm, but what does your "mkosi.build" script contain? Apparently it contains "git clean -dfqx" as first command? But if you have that there, then you tree really should be a git checkout... This looks like a problem with your setup/script, not so much with mkosi...

(is this the systemd build tree? i figure the mkosi.build script included in it doesn't really work if you use it on a plain directory tree, it only works with real git check outs, as it uses "git -dfqx" to remove all cruft for trying to build... I figure we could make this command non-fatal, so that it works outside of git trees too, under the assumption that those are clean enough anyway, making this call unncessary)

**Comment by poettering** [comment]
Anyway, closing, as I am pretty sure the systemd mkosi.build script is at fault here, and I am working on a fix for that, making the clean-up for that non-fatal

**Comment by keszybz** [comment]
Yeah, this was in the systemd build tree. I actually have a better fix for that queued up locally: detect if mkosi is being run in a git repo and use git ls-files to only copy files that are not ignored by git. This actually makes mkosi behave much better in systemd tree, and avoids a lot of needless copying of files and then removing them. I'll submit the patches...
