### ISSUE TITLE
Cannot enable services in post installation script

### ISSUE THREAD

**Issue by thedrow** [systemd/mkosi#262]
Since we're running [systemd as PID2](https://github.com/systemd/mkosi/blob/master/mkosi#L913) inside the container when I try to enable a service I get the following error messages:
`System has not been booted with systemd as init system (PID 1). Can't operate.`

Is there a reason why we're running systemd as PID 2?
Can we introduce a flag/configuration option to disable this behavior?

**Comment by lucaswerkmeister** [comment]
We’re not running systemd as PID2 – we’re running any workspace command as PID2, because most commands don’t properly support running as PID1 (i. e. they probably won’t reap zombies). If you’re running `systemd` or `systemctl` as part of your build, that’s something specific to your setup, and it would probably be useful to provide more details so we can debug it :)

**Comment by poettering** [comment]
you should be able to set `$SYSTEMD_OFFLINE=1` to force systemctl to operate client side for all enable/disable operations. And we should probably set that for all our calls.

That env var is only available in recent systemd versions though, for older once, you can use --root=/ as  a hack to make systemctl not talk to PID 1.
