### ISSUE TITLE
Not supporting ImageId= when building multiple images breaks system extension image building

### ISSUE THREAD

**Issue by mcassaniti** [systemd/mkosi#2938]
### mkosi commit the issue has been seen with

24

### Used host distribution

Ubuntu 24.04

### Used target distribution

Ubuntu 24.04

### Linux kernel version used

6.8.0-39-generic

### CPU architectures issue was seen on

x86_64

### Unexpected behaviour you saw

Sub-images no longer allow `ImageId=`

Thinking logically, the main image that could be running on a laptop might have an image ID of laptop. If you want to build several system extension images which need their own image ID then you're now out of luck. It makes complete sense to use the laptop image as a base and build the extension images as an overlay.

### Used mkosi config

```ini
[Output]
ImageId = ...
```

### mkosi output

```sh
Setting ImageId cannot be configured in subimage ...
```

**Comment by DaanDeMeyer** [comment]
@NekkoDroid So I know you asked for image ID and image version to be universal but looking at this I think that's wrong. I'm going to change this back to be non-universal, is that OK with you?

**Comment by NekkoDroid** [comment]
> is that OK with you?

In theory it should be fine, although not ideal.

For example I am currently outputting the main image as `disk`, but the actual base tree for the main image is built as a subimage and output as `tar`, so that sysext can build ontop of that. So the subimage still needs to know the `ImageId` it needs to work with and duplicating `ImageId` for that doesn't exactly sound right (since I also set `UnifiedKernelImageFormat=%i_%v` in the main image).

I mainly see 2 ways this possibly could be addressed:
1. Have `ImageId`/`ImageVersion` inherited by default, but overridable
2. Also read `SYSEXT_ID`/`SYSEXT_VERSION_ID` (and equivalent for confext) from the environment variables

I think 2 would be the better option for configuring all the entries in the `extension-release` file, as that would also allow to actually set an non-hardcoded value to `SYSEXT_SCOPE` (that currently has a questionable value) https://github.com/systemd/mkosi/blob/aacfae64a9bbad29494510f3c4d6c9d54cf50b6e/mkosi/__init__.py#L303

**Comment by mcassaniti** [comment]
What's the limitation with inheriting the image ID and version?

**Comment by NekkoDroid** [comment]
The main limitation with inheriting the value would most likely be that it currently isn't implemented (haven't actually checked) and would be another special case for the config parsing.

**Comment by DaanDeMeyer** [comment]
Inherit but overridable might be the correct behavior for these though. The same applies when building the initramfs as a subimage. Let's see if we can fit this in without too much effort.

**Comment by NekkoDroid** [comment]
I think it would also still be worth while to also read the value from env vars, just to be able to configure `SYSEXT_SCOPE`.
