### ISSUE TITLE
[crash] mkosi-git AUR crashes to TTY

### ISSUE THREAD

**Issue by tr37ion** [systemd/mkosi#325]
On Arch the [mkosi-git](https://aur.archlinux.org/packages/mkosi-git/) AUR crashes to TTY after `Generate locales...`. Installing the default [mkosi](https://aur.archlinux.org/packages/mkosi/) AUR works just fine. Possible regression ?!

![mkosi](https://user-images.githubusercontent.com/1538617/52365517-f603ce80-2a47-11e9-8275-abd3e27410db.gif)

**Comment by lucaswerkmeister** [comment]
Possible, it’s been a while since the last release :/

Can you share the full command line to reproduce this?

**Comment by lucasdemarchi** [comment]
For me it's crashing much earlier when downloading keys.

```
sudo mkosi -d arch --default /dev/null --root-size=2G
```

crashes for me on Fedora with:

```
:: Import PGP key 256E/1A60DC44245D06FEF90623D6EEEEE2EEEE2EEEEE, "Gaetan Bisson <bisson@gaati.org>", created: 1998-03-24? [Y/n] 
(121/121) checking package integrity                                               [###############################################] 100%
error: libxml2: signature from "Levente Polyak (anthraxx) <levente@leventepolyak.net>" is unknown trust
:: File /var/tmp/mkosi-__fdh4oy/root/var/cache/pacman/pkg/libxml2-2.9.9-1-x86_64.pkg.tar.xz is corrupted (invalid or corrupted package (PGP signature)).
Do you want to delete it? [Y/n] 
```

Changing the SigLevel to "Never",  "fixes" it. I'm not sure this was actually a change in mkosi, but rather in Arch itself.

**Comment by op3** [comment]
The last thing that can be seen in the GIF before the crash is the output of `fuser`. This is the line that causes this problem:

https://github.com/systemd/mkosi/blob/80c7161111aaa9c7cc3760ff8f2b60bf9eb5f4bb/mkosi#L1846

Instead of killing only container-related processes, *all* processes on the host system are killed. I *can not* reproduce the problem by running

    mkosi -d arch --root-size=2G

(on Arch). However, I *can* reproduce the problem by running

    mkosi -d arch -t directory

(also on Arch). The problem does not occur if the mentioned line is removed.

**Comment by lucasdemarchi** [comment]
ugh. right, my bad.  That fuser command won't work with `-t directory`, not even if we bind mount root, which was the first thing I thought to solve. I will need to think in another way to do that.

**Comment by tr37ion** [comment]
The fix works for me. Thanks.
