### ISSUE TITLE
Is it time to tag another release?

### ISSUE THREAD

**Issue by NeilW** [systemd/mkosi#414]
All the Distros are still using v5 codebases from a year ago that have multiple issues with it. Including Ubuntu 20.04 and likely Fedora 32.

**Comment by svenstaro** [comment]
@DaanDeMeyer could you look into this?

**Comment by DaanDeMeyer** [comment]
I would like to get #504 merged and I still want to add boot integration tests for QEMU to CI so we have a clear idea of what works and what doesn't work. That will also uncover some more bugs that we should fix. After that we can do a release I think.  

@behrmann What do you think? I was thinking of doing this release without a news file since we'd have to scour the git logs to get all of the improvements and features out. We can add one after this release and start recording changes in there.

**Comment by behrmann** [comment]
I think we should maybe cut a release before #504 is merged. It is supposed to be a noop, but it is a significant change and I think that enough fixes and features have accumulated since v5 to warrant a release. 

I think it would also be ok to cut a release without a NEWS file, but I've quickly skimmed `git log --online v5..` and I think we could just write one with the highlight features being
- Mageia support
- image minimisation support
- using unified kernel images throughout
- `--qemu-headless`

**Comment by DaanDeMeyer** [comment]
@behrmann My idea behind merging #504 first was that we can build and attach the zipapp to the github release for easy access by users from distros that lag behind a bit on packaging new mkosi versions.

I'll try and do a PR that adds a NEWS file with some stuff in it.

**Comment by svenstaro** [comment]
Sooo how about a release now? :)

**Comment by behrmann** [comment]
I think the last thing missing was #523

**Comment by DaanDeMeyer** [comment]
Just pushed a new release (v6 tag), signed with my gpg key. I uploaded my gpg key to https://keyserver.ubuntu.com/ as well. Let me know if anything else is needed.

cc @poettering @keszybz (Just keeping you guys in the loop)

**Comment by keszybz** [comment]
> Just pushed a new release (v6 tag), signed with my gpg key.

Hooray!
