### ISSUE TITLE
Is there any use for luks support?

### ISSUE THREAD

**Issue by ingobecker** [systemd/mkosi#42]
I have created a fork and added basic [luks support](https://github.com/ingobecker/mkosi/commit/8a1c3f18b2108b7f13c82243660098d746c9d6e6)  in order to boostrap images that are fulldiskencrypted. I'm using mkosi to bootstrap images which i can later copy on bare metal machines (or VMs). I'm aware of the fact, that systemd-nspawn doesn't support luks partitions and i'm not sure if it makes any sense to use encrypted partitions in containers. I just wanted to mention my fork and ask if it makes sense beyond bootstraping bare metal images. If so, i could clean up my code and create a pull request.

**Comment by poettering** [comment]
I think LUKS support would be great to have (and direct LUKS support in nspawn would be great too, and dm-verity support would be great too). So please submit a PR!

**Comment by ingobecker** [comment]
There are still some parts missing like encrypting swap partitions, supplying luks format parameters and a way to include keyfiles into the resulting image (which may not be needed once systemd-nspawn is able to handle luks partitions). I'm working on it and i will have a look for debian support as well, when i'm done the named features. I will create a PR once i think arch support is working in a stable manner.

**Comment by poettering** [comment]
I wouldn't make too many things configurable, in fact I'd make this a single option that can have three values:

a) `off` — no encryption is done
b) `data` — the root partition is not encrypted (except on btrfs), but the /home and /srv partitions are, including swap
c) `all` — all partitions are encrypted, including swap

I am not convinced there's really value in configuring things in more detail.

And regarding the swap, I think we should probably never use LUKS for that by default. Instead, have an extra GPT partition flag. If that's set on a swap partition we should set up a raw dm-crypt with a random key on boot and invoke mkswap accordinly on it.

**Comment by ingobecker** [comment]
Ok, so how do you think the key should be supplyed?
At the moment, you can setup a passphrase by directly supplying it as a commandline argument when invoking mkosi or by setting it inside a mkosi.default file. It is also possible to insert a passphrase interactively while the image is created. There is also the possibility to use a keyfile. Which way do you think is appropriate?

There are also distinct keys to setup for the different partitions. Do you think all partitions should be using the same passphrase/keyfile?

What should be done about encryption details? Should we just go with the defaults, crypsetup is using?

**Comment by ingobecker** [comment]
Another option would be to have a keyfile created automatically.

**Comment by poettering** [comment]
Well, passing it on the command line is always less than idea, since the command line shows up in "ps". I think a behaviour like this would make sense: if there's a file "mkosi.passphrase" in the directory we are running from, then use that (and warn if the file has access rights more liberal than 0600...). If the file doesn't exist, but encryption is requested, then prompt the user for the passphrase. And that's all I'd support for the beginning.

And I think we should use the same key for all partitions we are about to encrypt. I doubt it's useful making things more complicated than that. And yes, I'd just use the defaults of cryptsetup, I think it's a good thing to outsource that problem to them.

**Comment by ingobecker** [comment]
Things are mostly implemented as proposed. One thing i came accross is, how newlines in `mkosi.passphrase` files should be handled. My current implementation simply strips them away, as newlines make no sense in a passphrase. I think it would make sense to display a warning in this case. Wich brings me to another point. In case the `mkois.passphrase` file has bad permissions, where should the warning be displayed? Currently, it's hard to recognize the warning due to stdout noise caused from installing pkgs etc. My suggestion would be to display them at the very end of the installation process.

Another thing missing is the swap encryption. I would suggest to create a crypttab entry as a workaround, as long as there is no native approach in place.

**Comment by poettering** [comment]
I figure we should treat them the safe way as for passphrase files referenced in /etc/crypttab, which expect no newline at the end, and take it binary...

Maybe we should simply fail with an error msg if the perms aren't right. That's safer and solves the problem with the stdout noise...

**Comment by poettering** [comment]
swap encryption is something that we should probably solve within the gpt-auto logic on the systemd side of things. And it probably needs to explicit support in mkosi at all, because the choice whether swaps shall be encrypted or not should not be encoded in unencrypted metadata, but should be configured either on the kernel cmdline or within the encrypted root partition in some kind (i.e. some configuration file the gpt-auto logic reads that says to always encrypt swap or never or so). hence: don't bother in mkosi with it...

**Comment by ingobecker** [comment]
I just passed the `mkosi.passphrase` along to `crypsetup`, so i don't have to deal with all the details handling a keyfile requires. Also made `mkosi` fail early, if perms are bad. Maybe it is better to name it `mkosi.keyfile` instead? That's actually how it's called by cryptsetup as there is no need, that this file requires to contain what is known as a passphrase(e.g. could contain data from /dev/urandom).

**Comment by poettering** [comment]
If you are content with your work, please post a PR against mkosi for it, and we can review it.
