### ISSUE TITLE
signed releases on github

### ISSUE THREAD

**Issue by shibumi** [systemd/mkosi#44]
Hello,
it would be awesome to have signed releases. Here is a cool tutorial for this:

https://wiki.debian.org/Creating%20signed%20GitHub%20releases

best regards,

chris

**Comment by lucaswerkmeister** [comment]
Is this mechanism orthogonal to tag signatures? GitHub added support for displaying those a while ago ([blog post](https://github.com/blog/2144-gpg-signature-verification)).

**Comment by shibumi** [comment]
Not really. In the new mechanism by github you sign tags or commits. With the suggested method you create a signed tarball. (I know tarball is so 10 years ago...but it's still the common way how the distributions download and package the software). It's not enough to have signed commits and signed tags, when everybody is just downloading the tarball with unsigned content. Thats why mkosi should also provide signed tarballs for distributions.

**Comment by lucaswerkmeister** [comment]
Okay, let me clarify my position a bit, because I think I actually agree with @shibumi. **We can sign the tag and/or the tarballs.**

Signing the git tag itself is done with `git tag -s` and embeds a PGP signature in the git tag object. @keszybz and @poettering have done this for v1, v2 and v3, and GitHub also displays this signature.

![screenshot from 2017-10-13 00-06-47](https://user-images.githubusercontent.com/2346599/31521606-73dcc6dc-afaa-11e7-9289-d3571ed1a9da.png)

(Disregard the “learn about signing *commits*” message – it’s the tag that’s signed, not the commit. Verify with `git verify-tag v3` and `git verify-commit v3^{commit}`.)

Independently of this, you can add a detached PGP signature to the release tarball generated by GitHub (or locally with `git archive`), following the instructions on the Debian wiki. As far as GitHub is concerned, this file is just another release artifact, but it lets users verify the tarball without having to either clone the full git repository (to verify the tag signature) or trust GitHub with the signature verification.

We can do just signed tags, just detached tarball signatures, or both. (That’s what I meant by orthogonal mechanisms.) Since we’ve already started signing tags, I think we should continue doing that, but we could also additionally add tarball signatures to future releases (or even to past ones, but it would be a bit weird to have a signature so much newer than the release).

**Comment by DaanDeMeyer** [comment]
We don't do this in systemd either it seems. If systemd starts doing this, we'll pick it up in mkosi as so please create an issue in the systemd repository if you're still interested in this
