### ISSUE TITLE
Purging the machine-id is incompatible with bootloader installation

### ISSUE THREAD

**Issue by keszybz** [systemd/mkosi#47]
Commit f5cafba17214c02f9f80bc5283a165054f6dc828 removed machine-id. The next step, installation of the kernel in boot, fails:
```
‣ Installing boot loader...
Could not determine your machine ID from /etc/machine-id.
Please run 'systemd-machine-id-setup' as root. See man:machine-id(5)
```
Those options are fundamentally incompatible. Should we disable machine-id purging if bootable=yes?

**Comment by poettering** [comment]
Hmm, which distro did you build here? On fedora this doesn't happen, since install_boot_loader() just copies two files in that case, and doesn't do anything else.

I figure for arch/debian we could simply swap the `install_boot_loader()` and `reset_machine_id()` invocations. This would then expose similar behaviour on fedora and debian/arch, as the machine ID will still be available at the time "kernel-install" is invoked.

With #46 applied the machine ID is stable during the entire build, but not commited to the image. This makes things pretty OK I think. This means of course that the dirs in the ESP use a machine ID that doesn't match the machine ID that is used at runtime, but that's fine I think (I mean, initrd machine IDs tend to be different than host machine IDs too, hence I think having a different machine ID for the boot loader is OK too). Of course, ideally we'd have all three in sync, but that only works if the machine ID is static and the boot loader always installed with it fully set up.

(I think in the long run we should probably switch over to using dracut's `--uefi` btw, which spits out a single EFI executable containing the kernel, the initrd, metadata and the kernel command line. This can then be signed with "pesign" as one blob. Kernel/initrd images like that can be installed into `$ESP/EFI/linux` (where sd-boot already looks), thus making it unnecessary to have a fixed machine ID. This is particularly relevant in a dm-verity world, where the root hash needs to be part of the kernel image, and hence can be signed.)

**Comment by keszybz** [comment]
Debian. I was testing systemd/systemd#4856.

> I figure for arch/debian we could simply swap the install_boot_loader() and reset_machine_id() invocations.

Or even move reset_machine_id until just before the image is unmounted.
