### ISSUE TITLE
RFE: Allow distro specific subdirectories in mkosi.default.d

### ISSUE THREAD

**Issue by DaanDeMeyer** [systemd/mkosi#506]
These only get applied for that specific distro. Also allow mkosi specific files in mkosi.default.d and the distro specific subdirectories. The last one found gets applied.

This is a backwards compatible way to get advanced per distro configuration.

If required we can go further and allow per release subdirectories in each distro directory and per architecture directories in each per release directory. Let's start with just distros though.

**Comment by DaanDeMeyer** [comment]
Adding this does make me a bit worried about the exponential amount of possible scenarios for config parsing. Right now, we have:

- mkosi.default and mkosi.default.d
- --default=<path> which also implies searching <path>.d
- mkosi.files
- --all-directory
- --directory

**Comment by dellgreen** [comment]
this would be nice, as i have up to now had to dynamically generate the mkosi directory structure and files so that i can organise a project as you outline by distro, version, debug/release variant and then finally by feature so that all the components that make up a feature can be kept together (very yocto like) ;)

**Comment by lucasdemarchi** [comment]
+1
