### ISSUE TITLE
Sign commits

### ISSUE THREAD

**Issue by svenstaro** [systemd/mkosi#517]
It seems that no commits in this repo are signed and that makes me a sad panda provided that this software is likely part of some important deployment configs. Could you start signing commits/tags?

Related: #44

**Comment by behrmann** [comment]
I think this is worth looking into. Signing the releases should be doable, since systemd does it as well.

I'm not entirely sure who would do the signing, since I don't know who is going to do the release. I'm also not entirely sure how large the benefit is, since - in the light of no working key distribution mechanism for GPG keys - it exchanges the trust into the immutability of git histories for the trust into a GPG key that is difficult to verify. Even though I'd rather put my faith in the community crying out loud if the history of the repository were arbitrarily rewritten, I'm still +1 in fulfilling this wish, if a way can be figured out who cuts releases and does the signing, so that this can be communicated.

**Comment by DaanDeMeyer** [comment]
This doesn't look all too hard to set up. I can create a gpg key and sign the release tag, let's not sign commits since systemd doesn't do that either I think.

**Comment by svenstaro** [comment]
Please see that this request is very specifically about signing commits and not releases. Commits should be signed by whoever did the commit. The other ticket should track release signing.

**Comment by DaanDeMeyer** [comment]
Signing commits is something where we'll follow the main systemd repository. We're not likely to start doing it for mkosi if systemd itself doesn't do it itself unfortunately.

**Comment by behrmann** [comment]
The merge commits in systemd are signed by a Github key (TIL this is a possibility), but regular commits are usually not signed, at least in the past month I haven't seen a signed non-merge commit. Maybe having Github sign the merges could be done as well, although I actually had to click the the "verified" sign on the commit to see, that it wasn't actually the commiter's key signing this commit, which is a bit unfortunate.

Besides that I'm fine with people signing their commits, but I wouldn't want to mandate it, since it's another hurdle for people to participate and - as argued above - doesn't buy us an awful lot, without a mechanism to attest that the keys actually belong to the people, which we don't have.

**Comment by DaanDeMeyer** [comment]
Let's close this, we'll sign tags but not individual commits, just like systemd does.
