### ISSUE TITLE
Optionally, right before completing set all mtimes to zero

### ISSUE THREAD

**Issue by poettering** [systemd/mkosi#687]
Our images are unfortunately currently mostly not reproducible, since the package manager has a lot of freedom of writing stuff to disk, and so have the file systems used as backend. But we can at least slightly improve things, so that the file manifests at least become reproducible a bit more: let's optionally reset the mtimes of everything in the root partition (not in the var/home/srv/… partitions) to zero right before completing things.

**Comment by DaanDeMeyer** [comment]
If we ever get things fully reproducible we maybe do double builds in CI to make sure it stays that way. I'm kinda sceptical we'll get there soon though.

**Comment by Foxboron** [comment]
Is there a list of directories which should not be zeroed?

**Comment by poettering** [comment]
> Is there a list of directories which should not be zeroed?

A simple approach might be to just zero the mtime of everything outside of /proc and /sys, and then wait for complaints where that broke anything.

**Comment by malt3** [comment]
Me and @katexochen would like to take a stab at this.
How would you handle this with regards to `SOURCE_DATE_EPOCH`?

Possible implementations:

- Just use `Environment=SOURCE_DATE_EPOCH=0`. This works well with other tools and doesn't need any more flags / parameters.
- Have `NormalizeMtimes=0` as a setting and allow arbitrary timestamps to be chosen).
- Have `ZeroMtimes` and some sensible fallback for cases where `SOURCE_DATE_EPOCH` is set.

@behrmann @DaanDeMeyer

**Comment by DaanDeMeyer** [comment]
See the discussion in https://github.com/systemd/mkosi/pull/1695

**Comment by malt3** [comment]
To inline this, and ensure this goes into the right direction:

> If $SOURCE_DATE_EPOCH is set, always use it.
If $SOURCE_DATE_EPOCH is not set and --reproducible is set, set mtimes to zero
If $SOURCE_DATE_EPOCH is not set and --reproducible is not set, don't touch mtimes

Adding a `--reproducible` flag and settings `SOURCE_DATE_EPOCH` if wasn't set by the user can be follow ups to that.

**Comment by DaanDeMeyer** [comment]
Sounds good, for now, let's just use `SOURCE_DATE_EPOCH` whenever it is set.

**Comment by keszybz** [comment]
> Adding a `--reproducible` flag and setting `SOURCE_DATE_EPOCH` if it wasn't set by the user can be follow ups to the initial PR for normalizing mtimes.

In the rpm world, we have the following:
- the changelog is generated from the commit list, with timestamps taken from the commit too
- the last changelog entry used to set $SOURCE_DATE_EPOCH
- $SOURCE_DATE_EPOCH is determines everything else in the usual fashion.

This is nice because without *any additional action* by the package maintainer, the builds are reproducible, and the mtime is set to a meaningful value. Nowadays VCS is used for everything, and one must do commits to do things, and from a commit we get an immutable but useful timestamp. I think we should do the same in mkosi, i.e. default to setting SOURCE_DATE_EPOCH from the last commit timestamp.

> Our images are unfortunately currently mostly not reproducible, since the package manager has a lot of freedom of writing stuff to disk, and so have the file systems used as backend.

So I'm not sure what the current status is, but with Daan's rework to use fs tools to write the file system from userspace, we might actually have full reproducibility. Once we reset the mtimes (and whatever other attributes get copied into the output), and if the inputs are sorted, the outputs should be reproducible. If not, that's a fixable bug in the tools.

**Comment by malt3** [comment]
> [...] we might actually have full reproducibility. 

I think that depends on your definition of reproducible. Currently you will get packages from a distribution repository and there is no user friendly way to prevent subsequent builds from installing different (newer) packages. I have ideas for solving this problem that should be straightforward to implement for mkosi and still have good UX. I'll try to write an issue with a proposal.

**Comment by keszybz** [comment]
Yeah, you need to pin package versions, and of course all other inputs. I mean that once that's done, the actual work done by mkosi might already be close to fully reproducible.

**Comment by Foxboron** [comment]
> I think that depends on your definition of reproducible. Currently you will get packages from a distribution repository and there is no user friendly way to prevent subsequent builds from installing different (newer) packages. I have ideas for solving this problem that should be straightforward to implement for mkosi and still have good UX. I'll try to write an issue with a proposal.

You need to take the package lock file `mkosi` produces and fetch all the package versions from some archive. It's not really hard to implement and both Debian and Arch already has existing tooling doing this.

See: https://github.com/archlinux/archlinux-repro

**Comment by malt3** [comment]
I think this can be resolved, since it is implemented with `mkosi --source-date-epoch=0`
