### ISSUE TITLE
proposal: let's drop black enforcement

### ISSUE THREAD

**Issue by keszybz** [systemd/mkosi#779]
Autoformatting is **good idea** in general, but in real life it is doesn't work too well.

First, black makes some very peculiar formatting choices, e.g. the use on double-quoted string even when there's no reason for this, and the rust-like extensive splitting to multiple lines with opening and closing parenthesis on multiple lines. This is different than the generally accepted traditional python style.

Second, in mkosi there is a lot of "table-like" code, e.g. various lists of identifiers and repeated definitions. Black doesn't (and probably cannot) understand that there's a repeatable structure to the code and tries to squish everything together to save space.

We *could* sprinkle `#fmt=off`  / `#fmt=on` in more places, but I don't like this approach. If there's a tool that gets in your way, but doesn't really offer any benefits, it's time to drop the tool. If some of us want to use black while editing, that's completely fine, but only use it for newly added or significantly rewritten chunks and where it makes sense.

Some particularly egregious examples:
![Screenshot from 2021-08-28 11-23-36](https://user-images.githubusercontent.com/349618/131650596-c2505027-c6e2-45e3-88ec-5dc6161b8aae.png)
![Screenshot from 2021-08-28 11-32-01](https://user-images.githubusercontent.com/349618/131650709-fc0c4680-5fac-40ff-aa28-f472fbb18527.png)
![Screenshot from 2021-09-01 11-55-48](https://user-images.githubusercontent.com/349618/131651658-5fc1f023-8119-413d-a704-6895288dfa49.png)
![Screenshot from 2021-09-01 11-56-50](https://user-images.githubusercontent.com/349618/131651780-2f7467bb-1d1b-4d8b-b9f7-db7ae2df9b84.png)

**Comment by DaanDeMeyer** [comment]
Sure, we can remove the enforcement, I don't mind too much either way. @behrmann will disagree I think though.

**Comment by keszybz** [comment]
I'm now preparing a patch that replaces os.path.join() with pathlib.Path(). This obviously touches a lot of code in a fairly trivial way, and I'm noticing how much the code is convoluted by the automatic formatting.

**Comment by behrmann** [comment]
> Sure, we can remove the enforcement, I don't mind too much either way. Though I think @behrmann will disagree.

Not opposed per se :) 

I agree, that sometimes black's formatting is not optimal, i.e. properly maintained style might be superior, but before black that was a bit on and off and some of the photon code even mixed in tabs for, so at least that should be something we catch otherwise. Even though black is not always optimal, I think there is some value in some static checking of formatting and not having to argue about it. (Which we nevertheless now are :) )

Of @keszybz's examples I only find the first one properly ugly. The second is *the* case for fmt directives and there's only finitely many of them. The third - I'd argue - is a good case for a multiline string and the last is borderline and probably an artifact of the long line setting we use.

**Comment by poettering** [comment]
Kinda sucks that such regimes don't even work in Python, where coding styles are much less varied than in C... :-(
