### ISSUE TITLE
Marketplace says that v8 is the latest version of mkosi

### ISSUE THREAD

**Issue by evverx** [systemd/mkosi#863]
Looking at https://github.com/marketplace/actions/setup-mkosi, it seems since v8 was released Marketplace hasn't been in sync with the mkosi repository.
![Screenshot 2021-11-26 at 10 08 33](https://user-images.githubusercontent.com/10195800/143540930-41c6ab85-6e19-4141-846e-ee51b845cf81.png)

**Comment by evverx** [comment]
The "releases" tab at https://github.com/systemd/mkosi/releases looks weird as well
![Screenshot 2021-11-26 at 10 11 02](https://user-images.githubusercontent.com/10195800/143541219-136f05c0-98e4-4179-a9d2-40a6703880bd.png)

**Comment by behrmann** [comment]
The latter is because we haven't done a release on Github yet. I think this was just forgotten.

The action being out of sync is probably because the last releases haven't been published on the marketplace. There is a check box
> Publish this release to the GitHub Marketplace
systemd must accept the GitHub Marketplace Developer Agreement. Contact an org admin to accept it.

But that's a checkbox probably only @poettering and @keszybz can check.

**Comment by keszybz** [comment]
Yeah, I had some doubts about the license agreement. We're still discussing this internally.

**Comment by evverx** [comment]
I wonder if in the meantime it would make sense to remove it from GitHub marketplace so as not to confuse anybody?

**Comment by evverx** [comment]
Looking at https://github.com/marketplace/actions/setup-mkosi and https://github.com/systemd/mkosi/releases, I think the issue can be closed.
