### ISSUE TITLE
Can not build images with latest version.

### ISSUE THREAD

**Issue by Edu4rdSHL** [systemd/mkosi#873]
Hello, I have the following files:

- `archlinux-tar.default`

```
[Distribution]
Distribution=arch

[Output]
Format=tar
Bootable=no
Hostname=archlinux
Output=/srv/www/nspawn.org/public/storage/archlinux/archlinux/tar/image.tar.xz
CompressOutput=xz

[Validation]
Sign=yes
Key=E605F310C46032EBD9EDDDA09F9B61E3E4EF5957
Password=root

[Content]
PostInstallationScript=archlinux.postinst
```

- `archlinux.postinst`

```
#!/bin/sh
# make sure systemd-networkd and systemd-resolved are running
systemctl enable systemd-networkd
systemctl enable systemd-resolved
# make sure we symlink /run/systemd/resolve/stub-resolv.conf to /etc/resolv.conf
# otherwise curl will fail
ln -sf /run/systemd/resolve/stub-resolv.conf /etc/resolv.conf
# Add pts/[0-4] to /etc/securetty to allow logins via `machinectl login`
{
  echo "pts/0"
  echo "pts/1"
  echo "pts/2"
  echo "pts/3"
  echo "pts/4"
} >> /etc/securetty
# Initialize mirrors
sed -i 's/#Server/Server/' /etc/pacman.d/mirrorlist
```

I'm trying to build the image using: `sudo /usr/bin/mkosi --default archlinux-tar.default --postinst-script=archlinux.postinst --cache=archlinux.cache`

But I get the following error: https://gist.github.com/Edu4rdSHL/87fec71a3fb959c48aed03ddd793be0c

The mkosi version that I'm using is 12, my host OS is ArchLinux with BTRFS filesystem.

**Comment by behrmann** [comment]
This looks like this is not our bug, since tar fails while compressing the image because `pxz` doesn't seem to do its job. 

If you need to use xz compression, have a look whether the regular xz binary works for you. I don't see `pxz` in the official Arch repos, so you might need to rebuild it from the AUR because of some library changes.

If you don't need xz compression, have a look whether something else, like zstd, works for you.

**Comment by Edu4rdSHL** [comment]
Thank you so much for catching the `pxz` state, it was the problem.

**Comment by behrmann** [comment]
Happy to help, wouldn't have been possible without this wonderfully complete bug report.
