### ISSUE TITLE
How to override /etc/fstab while building?

### ISSUE THREAD

**Issue by pPanda-beta** [systemd/mkosi#874]
I've currently create an Ubuntu image with mkosi. The image holds 5 partitions. 
1. ESP
2. Swap
3. /srv
4. root
5. dm-verity

Now I've a requirement of keeping two such os (different versions) side by side on same disk. The way I'm installing those is like:
- First copy all 5 partitions to `/dev/sda1.../dev/sda5`
- Then copy the 5 partitions of next os to `/dev/sda6.../dev/sda10`
- All partitions are created using gdisk and very carefully the GUIDs are copied.

Now I'm using 
```
efibootmgr --create --disk /dev/sda --part 1  --label "Debug ubuntu1"  --loader "EFI\Linux\linux-5.4.0-91-generic-22c1459f3ed19d16d137682e5ab4373e11eb11539429990751bef6ec194332f6.efi" --unicode 'debug root=PARTUUID=22c1459f-3ed1-9d16-d137-682e5ab4373e'
```
to mention the root partition. 

This works fine and loads the correct root partition. But the problem exists for swap and /srv partitions. 
As per the Discoverable Partition Specification (DPS), which is basically a simple for-loop : 
 https://github.com/systemd/systemd/blob/67cb0d4725af7593440c50125a63d01963d54d13/src/shared/dissect-image.c#L886
and a simple type and flag check https://github.com/systemd/systemd/blob/67cb0d4725af7593440c50125a63d01963d54d13/src/shared/dissect-image.c#L960-L970 **both the OS is always picking up the same /srv and swap partition.**

DPS has never considered a dual booting scenario. Also there is no kernel parameter like `mount.srv=PARTUUID...` or `mount.swap=PARTUUID=...`
**The only way we can override this partition mapping is via an `/etc/fstab` with PARTUUIDs.**

## Expected: 
1. Two ubuntu distributions reside on same disk
2. systemd will pick up the correct /srv and /swap partition based on pre defined `/etc/fstab`

 
## Actual: 
1. There is no way to inject an `/etc/fstab` while building the image via mkosi.
2. If we modify the `/etc/fstab` after image is built, it will fail the hash matching for `dm-verity`

**Comment by DaanDeMeyer** [comment]
/etc/fstab is probably not the way to this, since like you found out, you get into trouble with dm-verity.

I figure the discoverable partitions spec should probably be extended with support for associating partitions with each other if that's at all possible. Then systemd-gpt-auto-generator can automatically load the correct side partitions to load after it figures out which root partition to load.

This isn't something we can fix in mkosi though. I'd suggest opening an issue in the systemd repository to request this functionality be added to the discoverable partitions spec.
