### ISSUE TITLE
ubuntu: Only install linux-generic if not specific kernel package was provided by the user

### ISSUE THREAD

**Issue by vt-alt** [systemd/mkosi#884]
Please replace base package `linux-generic` with `linux-virtual` for Ubuntu. 

mkosi is mainly used for KVM based CI testing, but `linux-generic` pulls `linux-firmware` which is not needed 200 Mb (wastes bandwidth and time). While `linux-virtual` is better suited for virtual machines.

```python
        if args.distribution == Distribution.ubuntu:
            add_packages(args, extra_packages, "linux-generic")
```
Thanks.

**Comment by vt-alt** [comment]
And I was unable to replace `linux-generic` with `linux-virtual` using `Packages` syntax (not with command line `-p`):
```
[Packages]
Packages=
        !linux-generic
        linux-virtual
```
But, even if it was replaceable it would be better to have right default package to save traffic.

**Comment by bluca** [comment]
> mkosi is mainly used for KVM based CI testing

Removing manually should work, but I'm not sure about this, it's supposed to work out of the box on hardware too

**Comment by behrmann** [comment]
Thanks for report! As @bluca says, removing should work, if it doesn't we need to look into that. I also agree that changing the default might not be the best idea, since (from other issues) we know, that people do use mkosi to generate images for bare metal deployments and they would then need to remember to pull in `firmware-linux` themselves. One possibility I could see would be to do for Ubuntu what we already do for Arch, have a list of official kernel packages and default to `linux-generic` if no other is given. This way only `linux-virtual` would need to be added to the list.

**Comment by DaanDeMeyer** [comment]
We don't install any kernel packages by default anymore, so let's close this one
