### ISSUE TITLE
Creating arch image from ubuntu/debian

### ISSUE THREAD

**Issue by leocrawford** [systemd/mkosi#971]
I'm trying to `mkosi -d arch` from an Ubuntu host, which results in:

    Error: pacman-key not found in PATH.

Checking `man` we see that "Any distro that packages pacstrap may be used to build Arch Linux images". I have installed `arch-install-scripts` which purports to contain `pacstrap`. 

```
> dpkg -L arch-install-scripts
/.
/usr
/usr/bin
/usr/bin/arch-chroot
/usr/bin/genfstab
/usr/share
/usr/share/bash-completion
/usr/share/bash-completion/completions
/usr/share/bash-completion/completions/arch-chroot
/usr/share/bash-completion/completions/genfstab
/usr/share/doc
/usr/share/doc/arch-install-scripts
/usr/share/doc/arch-install-scripts/README.md
/usr/share/doc/arch-install-scripts/changelog.Debian.gz
/usr/share/doc/arch-install-scripts/copyright
/usr/share/man
/usr/share/man/man8
/usr/share/man/man8/arch-chroot.8.gz
/usr/share/man/man8/genfstab.8.gz
/usr/share/zsh
/usr/share/zsh/site-functions
/usr/share/zsh/site-functions/_archinstallscripts
```

Checking debian package info (https://packages.debian.org/unstable/arch-install-scripts) we can see that indeed `pacstrap` is not included, but is mentioned in 22-1.. so possible regression.

Normally I'd open a issue on the debian package maintainer, but I searched the `mkosi` source for `pacstrap` and it doesn't appear to be used (though it is mentioned in comments) . So, question is `pacstrap` the real dependency I need to fix to run this from debian, or is it something else?

**Comment by behrmann** [comment]
That is a tricky situation and neither our bug nor really Debian's. It's a bit weird.

On Arch `arch-install-scripts` contains `arch-chroot`, `genfstab` and `pacstrap`. Apparently, Debian packaged `arch-install-scripts`, because they found `arch-chroot` and `genfstab` useful (it says something along those lines in the package description). 

These tools are not really dependent on anything Arch, the former is just a `chroot` that also sets up pseudo filesystems and the former generates an `fstab` from `mtab`. They did remove `pacstrap`, because that is just a wrapper for pacman (one we're doing without, just using plain pacman). Unfortunately pacman is not packaged in Debian, so including `pactstrap` is pretty pointless.

What you can do, is file a wishlist bug against `arch-install-scripts` to include `pacstrap` (and package pacman), but this won't solve your problem in a timely manner. You can have a look at mkosi's CI setup, which builds pacman from source, and replicate that.

**Comment by DaanDeMeyer** [comment]
We don't even use pacstrap anymore so we should update the docs if that's still mentioned anywhere
